version: '3'
services:
  windows:
    image: dockurr/windows:latest
    container_name: tiny10_space
    privileged: true
    environment:
      # Прямая ссылка на Tiny10 21H2 x64
      VERSION: "https://archive.org/download/tiny-10-21h2-x64-2209/tiny10%2021H2%20x64%202209.iso"
      RESOLUTION: "1366x768"
    ports:
      - "8006:8006"
    restart: unless-stopped
